export const constQuery = `{
	monthlycost{
                          mtdCost
                          monthlyCost
                          mtdCostInPercentage
                          costForLastMonth
                          costStatus
                          costPercentage
                          lastMonthCostInPercentage
                        }
  insightData{
                                id
                                msg
                                type
                            }
  optimizationData{
                                id
                                value
                                saving
                                type
                            }
  savingopportunitiesData{
                                id
                                name
                                amount
                                suggestions
                            }
  barchartdata{
    dataSets {
      name
      label
      data{
        value
      }
      monthlyForecast
    }
    datalabels {
      labels
    }
    averageCost
  }
  toptenconstchanges{
        text
        price
        costStatus
    }
  
  costbysites{
          dataSets{
            name
            data{
              value
            }
            label
          }
          datalabels{
            value
          }
        }
  costaccount{
            name
            cost
            grdata
            resourcecount
        }
  costbyaccdata{
            id
            name
            y
        }
}`